<!-- header.inc -->
<header>
  <nav>
    <div class="logo">
      <img src="images/logo.png" alt="Prime Nova Gaming Logo" class="logo-img">
      PRIME NOVA GAMING
    </div>

    <ul class="nav-list">
      <li><a href="index.php">Home</a></li>
      <li><a href="about.php">About</a></li>
      <li><a href="apply.php">Apply</a></li>
      <li><a href="jobs.php">Jobs</a></li>
      <li><a href="mailto:info@primenovagaming.com.au">Email</a></li>
    </ul>
  </nav>
</header>
