<nav>

    <li><a href="index.php">Home</a></li>
    <li><a href="about.php">About</a></li>
    <li><a href="apply.php">Apply</a></li>
    <li><a href="jobs.php">Jobs</a></li>
    <li><a href="login.php">Login</a></li>
    <li><a href="manager_registration.php">Manager</a></li>
    <li><a href="manage.php">Manage</a></li>
    <li><a href="enhacements.php">Enhancements</a></li>
    <li><a href="mailto:info@primenovagaming.com.au">Email</a></li>
 
</nav>
